package philosopher

import (
	"context"
	"fmt"

	"github.com/eduzgun/gke-microservices/internal/db"
	"github.com/eduzgun/gke-microservices/internal/models"
	"github.com/jackc/pgx/v5/pgtype"
)

type philosopherRepoImpl struct {
	queries db.Querier
}

type PhilosopherRepo interface {
}

func (pr *philosopherRepoImpl) GetPhilosophers(ctx context.Context) ([]models.Philosopher, error) {
	// These philosophers are of a different model, one that is generated by sqlc (it lies in the storage layer)
	dbPhilosophers, err := pr.queries.ListPhilosophers(ctx)
	if err != nil {
		return nil, fmt.Errorf("listing philosophers with querier: %w", err)
	}

	// These philosophers are of my own model in the repository and service layer
	// We are decoupling storage to presentation this way
	// We need to map the models
	philosophers := make([]models.Philosopher, 0, len(dbPhilosophers))
	for _, dbPhilo := range dbPhilosophers {
		philosophers = append(philosophers, models.Philosopher{
			ID:          int(dbPhilo.ID),
			Name:        dbPhilo.Name,
			DateBorn:    pgTextToString(dbPhilo.DateBorn),
			DateDied:    pgTextToString(dbPhilo.DateDied),
			Birthplace:  pgTextToString(dbPhilo.Birthplace),
			Interests:   dbPhilo.Interests,
			PortraitURI: pgTextToString(dbPhilo.PortraitUri),
			Bio:         pgTextToString(dbPhilo.Bio),
			CreatedAt:   dbPhilo.CreatedAt.Time,
		})
	}

	return philosophers, nil
}

// Helper to convert pgtype.Text to string
func pgTextToString(t pgtype.Text) string {
	if t.Valid {
		return t.String
	}
	return ""
}
