// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: interactions.sql

package db

import (
	"context"
	"time"
)

const countLikesByPhilosopher = `-- name: CountLikesByPhilosopher :one
SELECT COUNT(*) FROM interactions
WHERE philosopher_id = $1 AND type = 'like'
`

func (q *Queries) CountLikesByPhilosopher(ctx context.Context, philosopherID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countLikesByPhilosopher, philosopherID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCommentInteraction = `-- name: CreateCommentInteraction :one
INSERT INTO interactions (
    user_id,
    philosopher_id,
    type,
    content,
    created_at
) VALUES ($1, $2, 'comment', $3, NOW()) RETURNING id, user_id, philosopher_id, content, created_at
`

type CreateCommentInteractionParams struct {
	UserID        int32  `json:"user_id"`
	PhilosopherID int32  `json:"philosopher_id"`
	Content       string `json:"content"`
}

type CreateCommentInteractionRow struct {
	ID            int32     `json:"id"`
	UserID        int32     `json:"user_id"`
	PhilosopherID int32     `json:"philosopher_id"`
	Content       string    `json:"content"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) CreateCommentInteraction(ctx context.Context, arg CreateCommentInteractionParams) (CreateCommentInteractionRow, error) {
	row := q.db.QueryRow(ctx, createCommentInteraction, arg.UserID, arg.PhilosopherID, arg.Content)
	var i CreateCommentInteractionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhilosopherID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createLikeInteraction = `-- name: CreateLikeInteraction :exec
INSERT INTO interactions (
    user_id,
    philosopher_id,
    type,
    content,
    created_at
) VALUES ($1, $2, 'like', NULL, NOW())
`

type CreateLikeInteractionParams struct {
	UserID        int32 `json:"user_id"`
	PhilosopherID int32 `json:"philosopher_id"`
}

func (q *Queries) CreateLikeInteraction(ctx context.Context, arg CreateLikeInteractionParams) error {
	_, err := q.db.Exec(ctx, createLikeInteraction, arg.UserID, arg.PhilosopherID)
	return err
}

const deleteInteraction = `-- name: DeleteInteraction :exec
DELETE FROM interactions
WHERE id = $1
`

func (q *Queries) DeleteInteraction(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteInteraction, id)
	return err
}

const getInteractionsByPhilosopher = `-- name: GetInteractionsByPhilosopher :many
SELECT 
    i.id,
    i.user_id,
    i.philosopher_id,
    i.type,
    COALESCE(i.content, '') as content,
    i.created_at,
    u.username
FROM interactions i
JOIN users u ON i.user_id = u.id
WHERE i.philosopher_id = $1
ORDER BY i.created_at DESC
`

type GetInteractionsByPhilosopherRow struct {
	ID            int32     `json:"id"`
	UserID        int32     `json:"user_id"`
	PhilosopherID int32     `json:"philosopher_id"`
	Type          string    `json:"type"`
	Content       string    `json:"content"`
	CreatedAt     time.Time `json:"created_at"`
	Username      string    `json:"username"`
}

func (q *Queries) GetInteractionsByPhilosopher(ctx context.Context, philosopherID int32) ([]GetInteractionsByPhilosopherRow, error) {
	rows, err := q.db.Query(ctx, getInteractionsByPhilosopher, philosopherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInteractionsByPhilosopherRow
	for rows.Next() {
		var i GetInteractionsByPhilosopherRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PhilosopherID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInteraction = `-- name: GetUserInteraction :one
SELECT id, user_id, philosopher_id, type, COALESCE(content, '') as content, created_at
FROM interactions
WHERE user_id = $1 
  AND philosopher_id = $2 
  AND type = $3
`

type GetUserInteractionParams struct {
	UserID        int32  `json:"user_id"`
	PhilosopherID int32  `json:"philosopher_id"`
	Type          string `json:"type"`
}

func (q *Queries) GetUserInteraction(ctx context.Context, arg GetUserInteractionParams) (Interaction, error) {
	row := q.db.QueryRow(ctx, getUserInteraction, arg.UserID, arg.PhilosopherID, arg.Type)
	var i Interaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhilosopherID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const hasUserLiked = `-- name: HasUserLiked :one
SELECT EXISTS (
    SELECT 1 FROM interactions
    WHERE user_id = $1 
      AND philosopher_id = $2 
      AND type = 'like'
)
`

type HasUserLikedParams struct {
	UserID        int32 `json:"user_id"`
	PhilosopherID int32 `json:"philosopher_id"`
}

func (q *Queries) HasUserLiked(ctx context.Context, arg HasUserLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLiked, arg.UserID, arg.PhilosopherID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
