// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Philosopher struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	DateBorn    pgtype.Text        `json:"date_born"`
	DateDied    pgtype.Text        `json:"date_died"`
	Birthplace  pgtype.Text        `json:"birthplace"`
	Interests   []string           `json:"interests"`
	PortraitUri pgtype.Text        `json:"portrait_uri"`
	Bio         pgtype.Text        `json:"bio"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
