// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Interaction struct {
	ID            int32     `json:"id"`
	UserID        int32     `json:"user_id"`
	PhilosopherID int32     `json:"philosopher_id"`
	Username      string    `json:"username"`
	Type          string    `json:"type"`
	Content       string    `json:"content"`
	CreatedAt     time.Time `json:"created_at"`
}

type Philosopher struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	DateBorn    string    `json:"date_born"`
	DateDied    string    `json:"date_died"`
	Birthplace  string    `json:"birthplace"`
	Interests   []string  `json:"interests"`
	PortraitUri string    `json:"portrait_uri"`
	Bio         string    `json:"bio"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
