// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: philosophers.sql

package db

import (
	"context"
)

const listPhilosophers = `-- name: ListPhilosophers :many
SELECT id, name, date_born, date_died, birthplace, interests, portrait_uri, bio, created_at
FROM philosophers
ORDER BY name
`

func (q *Queries) ListPhilosophers(ctx context.Context) ([]Philosopher, error) {
	rows, err := q.db.Query(ctx, listPhilosophers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Philosopher
	for rows.Next() {
		var i Philosopher
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DateBorn,
			&i.DateDied,
			&i.Birthplace,
			&i.Interests,
			&i.PortraitUri,
			&i.Bio,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
