// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: philosophers.sql

package db

import (
	"context"
)

const createPhilosopher = `-- name: CreatePhilosopher :one
INSERT INTO philosophers (
    name, date_born, date_died, birthplace, interests, portrait_uri, bio, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
)
RETURNING id
`

type CreatePhilosopherParams struct {
	Name        string   `json:"name"`
	DateBorn    string   `json:"date_born"`
	DateDied    string   `json:"date_died"`
	Birthplace  string   `json:"birthplace"`
	Interests   []string `json:"interests"`
	PortraitUri string   `json:"portrait_uri"`
	Bio         string   `json:"bio"`
}

func (q *Queries) CreatePhilosopher(ctx context.Context, arg CreatePhilosopherParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPhilosopher,
		arg.Name,
		arg.DateBorn,
		arg.DateDied,
		arg.Birthplace,
		arg.Interests,
		arg.PortraitUri,
		arg.Bio,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getPhilosopher = `-- name: GetPhilosopher :one
SELECT id, name, date_born, date_died, birthplace, interests, portrait_uri, bio, created_at
FROM philosophers
WHERE id = $1
`

func (q *Queries) GetPhilosopher(ctx context.Context, id int32) (Philosopher, error) {
	row := q.db.QueryRow(ctx, getPhilosopher, id)
	var i Philosopher
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DateBorn,
		&i.DateDied,
		&i.Birthplace,
		&i.Interests,
		&i.PortraitUri,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const listPhilosophers = `-- name: ListPhilosophers :many
SELECT id, name, date_born, date_died, birthplace, interests, portrait_uri, bio, created_at
FROM philosophers
ORDER BY name
`

func (q *Queries) ListPhilosophers(ctx context.Context) ([]Philosopher, error) {
	rows, err := q.db.Query(ctx, listPhilosophers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Philosopher
	for rows.Next() {
		var i Philosopher
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DateBorn,
			&i.DateDied,
			&i.Birthplace,
			&i.Interests,
			&i.PortraitUri,
			&i.Bio,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
